version: "3.8"

x-services:
  common: &common
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    restart: always

services:
  rnacos:
    <<: *common
    container_name: rnacos
    image: qingpan/rnacos:stable
    ports:
      - "8848:8848"
      - "9848:9848"
      - "10848:10848"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - RUST_LOG=info
      - RNACOS_HTTP_PORT=8848
      - RNACOS_GRPC_PORT=9848
      - RNACOS_HTTP_CONSOLE_PORT=10848
      - RNACOS_CONSOLE_LOGIN_ONE_HOUR_LIMIT=5
      - RNACOS_RAFT_SNAPSHOT_LOG_SIZE=10000
      - RNACOS_ENABLE_NO_AUTH_CONSOLE=false
