name: Check Markdown links

on:
  push:
    branches:
      - main

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - uses: gaurav-nelson/github-action-markdown-link-check@v1