name: Docker typecho

on:
  push:
    branches:
      - master

env:
  CONTEXT: typecho
  FILE_PATH: typecho
  REPO_NAME: lvillis/typecho

jobs:
  job:
    if: "contains(github.event.head_commit.message, 'build.all') || contains(github.event.head_commit.message, 'build.typecho')"
    env:
      TAG_NAME: latest
    name: latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.FILE_PATH }}/${{ env.TAG_NAME }}.Dockerfile
          push: true
          tags: ${{ env.REPO_NAME }}:${{ env.TAG_NAME }}
          cache-from: type=registry,ref=${{ env.REPO_NAME }}:${{ env.TAG_NAME }}
          cache-to: type=inline